// constants/typography.ts
export const typography = {
  fontFamily: {
    jakarta: 'PlusJakartaSans-Regular',
    'jakarta-bold': 'PlusJakartaSans-Bold',
    'jakarta-medium': 'PlusJakartaSans-Medium',
    'jakarta-semibold': 'PlusJakartaSans-SemiBold',
    'jakarta-extrabold': 'PlusJakartaSans-ExtraBold',
  },
  fontSize: {
    'type-9': ['9px', { lineHeight: '10.8px', letterSpacing: '0px' }],
    'type-9-bold': ['9px', { lineHeight: '14.4px', letterSpacing: '1px' }],
    'type-10': ['10px', { lineHeight: '12px', letterSpacing: '0px' }],
    'type-10-tracked': ['10px', { lineHeight: '16px', letterSpacing: '1px' }],
    'type-10-alt': ['10px', { lineHeight: '12px', letterSpacing: '1px' }],
    'type-11': ['11px', { lineHeight: '13.2px', letterSpacing: '0px' }],
    'type-11-tracked': ['11px', { lineHeight: '17.6px', letterSpacing: '1px' }],
    'type-11-tight': ['11px', { lineHeight: '13.2px', letterSpacing: '0.2px' }],
    'type-11-loose': ['11px', { lineHeight: '18.7px', letterSpacing: '0.2px' }],
    'type-11-semibold': ['11px', { lineHeight: '13.2px', letterSpacing: '0px' }],
    'type-12': ['12px', { lineHeight: '14.4px', letterSpacing: '0px' }],
    'type-12-base': ['12px', { lineHeight: '19.2px', letterSpacing: '0px' }],
    'type-12-body': ['12px', { lineHeight: '20.4px', letterSpacing: '0px' }],
    'type-12-alt': ['12px', { lineHeight: '18px', letterSpacing: '0px' }],
    'type-13': ['13px', { lineHeight: '15.6px', letterSpacing: '0px' }],
    'type-13-base': ['13px', { lineHeight: '22.1px', letterSpacing: '0px' }],
    'type-13-alt': ['13px', { lineHeight: '20.8px', letterSpacing: '0px' }],
    'type-13-tight': ['13px', { lineHeight: '19.5px', letterSpacing: '-0.25px' }],
    'type-13-compact': ['13px', { lineHeight: '18.2px', letterSpacing: '-0.5px' }],
    'type-14': ['14px', { lineHeight: '22.4px', letterSpacing: '0px' }],
    'type-14-base': ['14px', { lineHeight: '16.8px', letterSpacing: '0px' }],
    'type-14-tight': ['14px', { lineHeight: '21px', letterSpacing: '-0.25px' }],
    'type-14-alt': ['14px', { lineHeight: '21px', letterSpacing: '0px' }],
    'type-14-loose': ['14px', { lineHeight: '23.8px', letterSpacing: '0px' }],
    'type-14-padded': ['14px', { lineHeight: '23.1px', letterSpacing: '0px' }],
    'type-14-tall': ['14px', { lineHeight: '25.2px', letterSpacing: '0px' }],
    'type-15': ['15px', { lineHeight: '18px', letterSpacing: '0px' }],
    'type-15-base': ['15px', { lineHeight: '24.75px', letterSpacing: '0px' }],
    'type-15-alt': ['15px', { lineHeight: '25.5px', letterSpacing: '0px' }],
    'type-15-tall': ['15px', { lineHeight: '22.5px', letterSpacing: '-0.25px' }],
    'type-15-spaced': ['15px', { lineHeight: '28.5px', letterSpacing: '0px' }],
    'type-16': ['16px', { lineHeight: '19.2px', letterSpacing: '0px' }],
    'type-17': ['17px', { lineHeight: '20.4px', letterSpacing: '0px' }],
    'type-17-base': ['17px', { lineHeight: '23.8px', letterSpacing: '-0.5px' }],
    'type-17-tall': ['17px', { lineHeight: '32.3px', letterSpacing: '0px' }],
    'type-17-alt': ['17px', { lineHeight: '27.2px', letterSpacing: '-0.5px' }],
    'type-18': ['18px', { lineHeight: '23.4px', letterSpacing: '-0.5px' }],
    'type-18-alt': ['18px', { lineHeight: '25.2px', letterSpacing: '-0.5px' }],
    'type-19': ['19px', { lineHeight: '26.6px', letterSpacing: '-0.5px' }],
    'type-20': ['20px', { lineHeight: '24px', letterSpacing: '0px' }],
    'type-20-alt': ['20px', { lineHeight: '28px', letterSpacing: '-0.5px' }],
    'type-21': ['21px', { lineHeight: '35.7px', letterSpacing: '-0.6px' }],
    'type-22': ['22px', { lineHeight: '30.8px', letterSpacing: '-0.5px' }],
    'type-22-base': ['22px', { lineHeight: '28.6px', letterSpacing: '-0.5px' }],
    'type-22-alt': ['22px', { lineHeight: '26.4px', letterSpacing: '0px' }],
    'type-23': ['23px', { lineHeight: '28.75px', letterSpacing: '-1px' }],
    'type-23-alt': ['23px', { lineHeight: '41.4px', letterSpacing: '0px' }],
    'type-24': ['24px', { lineHeight: '33.6px', letterSpacing: '-0.8px' }],
    'type-25': ['25px', { lineHeight: '31.25px', letterSpacing: '-0.8px' }],
    'type-25-base': ['25px', { lineHeight: '32.5px', letterSpacing: '-0.5px' }],
    'type-25-alt': ['25px', { lineHeight: '30px', letterSpacing: '0px' }],
    'type-25-tight': ['25px', { lineHeight: '35px', letterSpacing: '-0.5px' }],
    'type-25-heavy': ['25px', { lineHeight: '31.25px', letterSpacing: '-1px' }],
    'type-26': ['26px', { lineHeight: '32.5px', letterSpacing: '-1px' }],
    'type-27': ['27px', { lineHeight: '33.75px', letterSpacing: '-1px' }],
    'type-27-alt': ['27px', { lineHeight: '37.8px', letterSpacing: '-0.5px' }],
    'type-29': ['29px', { lineHeight: '36.25px', letterSpacing: '-1px' }],
    'type-31': ['31px', { lineHeight: '38.75px', letterSpacing: '-1px' }],
    'type-45': ['45px', { lineHeight: '54px', letterSpacing: '0px' }],
    'type-46': ['46px', { lineHeight: '55.2px', letterSpacing: '0px' }],
    'type-69': ['69px', { lineHeight: '82.8px', letterSpacing: '-4px' }],
  },
};